### ISSUE TITLE
Role fails to update alternatives for most clang versions

### ISSUE THREAD

**Issue by nre-ableton** [Teebor-Choka/Provisioning---Ansible-role-dev#2]
Hi, first of all, thanks for releasing v1.0.1 and v1.0.3. Since v1.0.1, I can't use this role to install clang versions other than 6.0. The role fails like so:

```
[2021-06-07T07:24:08.932Z] TASK [teebor_choka.clang : update alternatives] ********************************
[2021-06-07T07:24:09.701Z] failed: [generic-linux-bionic-test_deploy] (item=clang-format) =>
{
   "ansible_loop_var" : "item",
   "changed" : false,
   "item" : "clang-format",
   "msg" : "Specified path /usr/bin/clang-format-5.0 does not exist"
}

```

It seems that the "update alternatives" task was updated in 274fea33501297c0450d24e2c22ab2f483730452 to support `clang-format` and `clang-tidy`. However, this is problematic because `clang-format` was only distributed in the `clang-6.0` package. `clang-tidy` isn't distributed in any of the `clang-*` packages. Generally speaking, users are expected to get `clang-format` and `clang-tidy` from the `clang-format-*` and `clang-tidy-*` packages, respectively.

I suggest that this role either installs the corresponding `clang-format-*`/`clang-tidy-*` packages for the given version, or that 274fea33501297c0450d24e2c22ab2f483730452 be reverted.

**Comment by Teebor-Choka** [comment]
Hi, for such a low version I get a completely different error:

```
     TASK [ansible-role-clang : ensure repo key presence] ***************************
    changed: [instance]
    
    TASK [ansible-role-clang : ensure repo presence] *******************************
    failed: [instance] (item=5) => {"ansible_loop_var": "repo_item", "changed": false, "msg": "apt cache update failed", "repo_item": 5}
    
    PLAY RECAP *********************************************************************
    instance                   : ok=5    changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    
ERROR: 
```
You can see more details here: https://github.com/Provizanta/ansible-role-clang/actions/runs/937476629

Nevertheless, I've updated the testing scenario in #3 to demonstrate how to test legacy versions. Feel free to make PR to that branch with a reasonable fix you propose. I'd say that prohibiting execution of versions <=5 would also be an acceptable solution.

**Comment by nre-ableton** [comment]
I left a [comment on your PR](https://github.com/Provizanta/ansible-role-clang/pull/3/files#r651542275), but I can also try to introduce a PR to test the different versions. I'll see what I come up with.

**Comment by nre-ableton** [comment]
Closing this issue because I think your PR can provide a better solution.
