### ISSUE TITLE
Add clangd to the list of optional clang tools

### ISSUE THREAD

**Issue by nbn22385** [Teebor-Choka/Provisioning---Ansible-role-dev#9]
## Proposed feature

I would like to have `clangd` (language server) be added to the list of optional packages.

## Rationale

 It is useful for development within language server clients, such as vim and neovim.

## Additional context

Proposed changes:
- vars/packages.yml: Add `clangd-{{ clang_version }}` to the `advanced_packages` list
- tasks/main.yml: Add `clangd` to the `loop` list in the `update alternatives` task

**Comment by Teebor-Choka** [comment]
Would you be willing to prepare a PR?

**Comment by nbn22385** [comment]
I can give it a shot.
